Keep apt-installed.txt for more workflows

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -42,6 +42,28 @@ jobs:
       - name: Install node dependencies
         run: |
           npm install eslint eslint-config-google eslint-plugin-html
+      - name: Publish documentation
+        if: ${{ github.event_name == 'push' }}
+        run: |
+          git clone --depth 1 ssh://git@github.com/bansan85/jessica-ci.git -b format
+          rm -Rf jessica-ci/*
+          apt list --installed > jessica-ci/apt-installed.txt
+          eval `ssh-agent`
+          ssh-add ~/.ssh/id_rsa
+          gpg --version
+          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPT_PASSWORD }}" --output .github/encrypted/github-ci-private.key .github/encrypted/github-ci-private.key.gpg
+          gpg --import .github/encrypted/github-ci-private.key
+          cd jessica-ci || exit 1
+          git config --global user.name "Github CI"
+          git config --global user.email "github-ci@le-garrec.fr"
+          git add .
+          if [ -n "$(git diff-index --name-only HEAD --)" ]; \
+          then \
+            git commit -S${{ secrets.GPG_KEY_ID }} -m "${{ github.event.head_commit.message }}" -m "Update from bansan85/jessica@$GITHUB_SHA"; \
+            git push || { echo "Failure git push" && exit 1; } \
+          fi
+          cd .. || exit 1
+          rm -Rf jessica-ci
       - name: formatter
         shell: bash
         run: |
diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -16,6 +16,12 @@ jobs:
       - uses: actions/checkout@v2
         with:
           token: ${{ secrets.WORKFLOW_TOKEN }}
+      - name: Install SSH key
+        if: ${{ github.event.workflow_run.head_branch == 'master' }}
+        uses: shimataro/ssh-key-action@v2
+        with:
+          key: ${{ secrets.GITHUBCI_PRIVATE_KEY }}
+          known_hosts: localhost ssh-rsa ${{ secrets.GITHUBCI_KNOW_HOSTS }}
       - name: 3rdparty
         run: sudo apt-get update && sudo apt-get install -yq libgtest-dev cppcheck iwyu shellcheck clang-tidy-11 clang-12
       - name: Set up Python "3.9"
@@ -31,6 +37,27 @@ jobs:
       - name: Install node dependencies
         run: |
           npm install eslint eslint-config-google eslint-plugin-html
+      - name: Publish documentation
+        if: ${{ github.event.workflow_run.head_branch == 'master' }}
+        run: |
+          git clone --depth 1 ssh://git@github.com/bansan85/jessica-ci.git -b linters
+          rm -Rf jessica-ci/*
+          apt list --installed > jessica-ci/apt-installed.txt
+          eval `ssh-agent`
+          ssh-add ~/.ssh/id_rsa
+          gpg --version
+          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPT_PASSWORD }}" --output .github/encrypted/github-ci-private.key .github/encrypted/github-ci-private.key.gpg
+          gpg --import .github/encrypted/github-ci-private.key
+          cd jessica-ci || exit 1
+          git config --global user.name "Github CI"
+          git config --global user.email "github-ci@le-garrec.fr"
+          git add .
+          if [ -n "$(git diff-index --name-only HEAD --)" ]; \
+          then \
+            git commit -S${{ secrets.GPG_KEY_ID }} -m "${{ github.event.head_commit.message }}" -m "Update from bansan85/jessica@$GITHUB_SHA"; \
+            git push || { echo "Failure git push" && exit 1; } \
+          fi
+          cd .. || exit 1
       - name: run-clang-tidy
         env:
           AR: /usr/bin/llvm-ar-12
